config/routes.rb
Planning::Application.routes.draw do

  resources :sessions, :only => [:create, :new]
  resources :events
  resources :users
  resources :conditions
  resources :comments
  resources :charges

  root :to => 'home#index'

  get  '/logout/'                 => 'sessions#logout', :as => 'logout'
  post '/invitees/:id'            => 'invitees#update', :as => 'update'
  get  '/users/:slug/admin'       => 'users#admin',     :as => 'admin'
  get  '/users/:slug/profile'     => 'users#profile',   :as => 'profile'
  post '/invitees/:id/conditions' => 'invitees#reset',  :as => 'reset'
  get  '/about'                   => 'home#about'
  get  '/stripe'                  => 'users#stripe'
  post '/validate/email'          => 'users#validate_email'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :require_login

  def index
    @user = current_user || User.new
  end

  def about
  end
end

app/views/home/_home_form_links.erb
<h3 id="home_form_links"><%= link_to "log in", '#', :class => "home_login" %> / <%= link_to "join", '#', :class => "home_join" %> / <%= link_to "about", about_path %></h3>

app/views/home/_home_join_form.erb
<div class="join_form">
  <h4>join</h4>

  <%= form_for @user do |u| %>
    <%= u.text_field     :first_name, :placeholder => "First name" %>
    <%= u.text_field     :last_name,  :placeholder => "Last name" %>
    <%= u.email_field    :email,      :placeholder => "Email" %>
    <%= u.password_field :password,   :placeholder => "Password" %>
    <%= u.password_field :password_confirmation, :placeholder => "Confirm Password" %>
    <div class="file-upload">
      <span>upload profile picture</span>
      <%= u.file_field     :profile_pic %>
    </div>
    <ul id="errors"></ul>
    <%= u.button "Create Account" %>
  <% end %>
  <%= link_to "close", '#', :class=> "home_form_close" %>
</div>

app/views/home/_home_login_form.erb
<div class="log_in_form">
  <h4>log in</h4>

  <%= form_tag sessions_path do %>
    <%= email_field_tag    :email,    nil, :placeholder => "Email", :autofocus => true %>
    <%= password_field_tag :password, nil, :placeholder => "Password" %>
    <%= button_tag "Sign In" %>
  <% end %>
  <%= link_to "close", '#', :class=> "home_form_close" %>
</div>

app/views/home/_home_tag_hover.erb
<p id="home_hover">
  Solve your group planning woes by giving everyone what they want. Get firm commitments from friends on attendance at events&#8212;concerts, shows, trips, you name it&#8212;and only commit to other events if your criteria is met. <br><br>With grou<span class="bolder">pact</span>, you don't have to commit to buying the ticket until your specific conditions have been satisfied! Don't want to be the only person going to a show? Just specify how many other people, or even what specific people, need to go before you're convinced!
</p>

app/views/home/_home_tagline.erb
<p id="home_intro">
  <strong>group planning, <span class="bolder">conditionally</span></strong>
</p>

app/views/home/about.erb
<div class="wrapper">

  <h1 id="faq_header"> Learn about the grou<span class="bolder">pact</span> developers! </h1>
  <span class="easter-egg">
  <%= image_tag 'squirrels.jpg', :id => 'faq_pic' %>
  </span>
  <div class='description_columns'>
    <div class='individual_description'>
      <h1 id="faq_header"><%= link_to 'Yannick', 'https://twitter.com/YDawant', :target => '_blank' %></h1>
      <p>
        To say Yannick is a social butterfly would be akin to mistaking a Hummer for your grandma's sedan. Somehow he manages to simultaneously rock out to German dubstep, geek out with his pair over Ruby and email his mom in French. It's downright impressive.
      </p>
    </div>

    <div class='individual_description'>
      <h1 id="faq_header"><%= link_to 'Mitch', 'https://twitter.com/dontmitch', :target => '_blank'  %></h1>
      <p>
        Mitch is our sometimes lovable robot of a team member. We're fairly sure that he doesn't sleep at night and simply plugs into a socket to stay energized. He also nerds out on algorithms and squashes bugs like a boss.
      </p>
    </div>

    <div class='individual_description'>
      <h1 id="faq_header"><%= link_to 'Andrew', 'https://twitter.com/astamm78' , :target => '_blank'  %></h1>
      <p>
        You know that guy who sits quietly in the back of the classroom and then casually crushes you come test day? That's Andrew. Oh, and his background in fine arts makes him unfairly good at front end design.
      </p>
    </div>

  </div>

  <div class="clear"></div>

</div>

app/views/home/faq.erb
<div class="wrapper">

  <h1 id="faq_header"> Learn about the grou<span class="bolder">pact</span> developers! </h1>

  <%= image_tag 'squirrels.jpg', :id => 'faq_pic' %>

  <div class='description_columns'>
    <div class='individual_description'>

      <h1 id="faq_header">Yannick</h1>
      <p></p>
    </div>

    <div class='individual_description'>
      <h1 id="faq_header">Mitch</h1>
      <p>Mitch has affectionately been deemed to be a robot. We on the grou<span class='bolder'>pact</span> team are fairly sure that he doesn't sleep at night and simply plugs into a socket and keeps on going.</p>
      <p>
      </p>
    </div>

    <div class='individual_description'>
      <h1 id="faq_header">Andrew</h1>
      <p>Andrew comes from a fine art background, spent years as an art director for a magazine publisher as well as some time doing freelance web-design. He's excited to get started with his career in web development. An avid photographer, cinema enthusiast, music buff and Cubs fan.</p>
    </div>

  </div>

  <div class="clear"></div>

</div>

app/views/home/index.html.erb
<%= render :partial => "home/home_tagline" %>

<%= render :partial => "home/home_tag_hover" %>

<div class="splash">
  <a href="/auth/twitter" class="auth_provider">
    <%= image_tag "omniauth/twitter_128.png", :alt => "Twitter" %>
  </a>

  <a href="/auth/facebook" class="auth_provider">
    <%= image_tag "omniauth/facebook_128.png", :alt => "Facebook" %>
  </a>

  <a href="/auth/google_oauth2" class="auth_provider">
    <%= image_tag "omniauth/google_oauth2_128.png", :alt => "Google" %>
  </a>

</div>


<% unless current_user %>

  <%= render :partial => "home/home_form_links" %>

  <%= render :partial => "home/home_login_form" %>

  <%= render :partial => "home/home_join_form" %>

<% end %>