config/routes.rb
Planning::Application.routes.draw do

  resources :sessions, :only => [:create, :new]
  resources :events
  resources :users
  resources :conditions
  resources :comments
  resources :charges

  root :to => 'home#index'

  get  '/logout/'                 => 'sessions#logout', :as => 'logout'
  post '/invitees/:id'            => 'invitees#update', :as => 'update'
  get  '/users/:slug/admin'       => 'users#admin',     :as => 'admin'
  get  '/users/:slug/profile'     => 'users#profile',   :as => 'profile'
  post '/invitees/:id/conditions' => 'invitees#reset',  :as => 'reset'
  get  '/about'                   => 'home#about'
  get  '/stripe'                  => 'users#stripe'
  post '/validate/email'          => 'users#validate_email'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :commit_date, :creator_id, :description, :title, :image,
                  :emails, :down_payment, :creator_api, :start_time
  serialize :emails

  acts_as_url :title
  acts_as_commentable

  has_many :invitees
  belongs_to :creator, :class_name => "User"
  has_many :users, :through => :invitees

  validates :title,       :length => {:minimum => 4,
                          :too_short => "must have at least %{count} letters"}
  validates :creator_id,  :presence => true
  validates :commit_date, :presence => true
  validate  :commit_date_is_in_the_future
  validate  :contains_one_email
  validate  :event_date_is_after_commit_date
  validates :down_payment, :format => {:with => /^\d{1,}$/}, :allow_nil => true

  before_save :downpayment_zero_to_nil
  before_save :reject_empty_emails

  ## To turn on custom image uploading for events
  # mount_uploader :image, ImageUploader

  def downpayment_zero_to_nil
    self.down_payment = nil if self.down_payment == 0
  end

  def waffling
    invitees.select { |invitee| invitee.status == "Pending" }
  end

  def waffling_by_user(user_id)
    waffling.select { |invitee| invitee.user_id == user_id }
  end

  def going
    invitees.select { |invitee| invitee.status == "Yes" }
  end

  def not_going
    invitees.select { |invitee| invitee.status == "No" }
  end

  def update_invitees_statuses(going)
    invitees.each { |invitee| invitee.update_attribute("status", "Pending") if invitee.status == "Yes" }
    going.each    { |invitee| invitee.update_attribute("status", "Yes") }
  end

  def start_time=(params)
    unless params['date'].empty?
      write_attribute :start_time, DateTime.parse(params['date'] + ' ' + params['time']) + 5.hours
    end
  end

  def commit_date=(date)
    if date
      date = Time.parse(date)
      write_attribute :commit_date, Time.new(date.year, date.month, date.day, 23, 59, 59, "-05:00")
    end
  end

  def down_payment=(down_payment)
    as_cents = (down_payment.to_f * 100).to_i unless down_payment.blank?
    write_attribute :down_payment, as_cents
  end

  def self.closeout_all_expired
    self.where('settled IS NULL AND commit_date < ?', Time.now).each do |event|
      event.update_invitees_statuses(Group.new(event.invitees).solve)
      event.settle_event
    end
  end

  def settle_event
    down_payment ? settle_with_payment : settle_without_payment
    self.update_attribute("settled", true)
  end

  def settle_with_payment
    invitees.each do |invitee|
      if invitee.user_id == self.creator_id
        EventMailer.notify_creator(invitee.user, event).deliver
      elsif invitee.status == "Yes"
        invitee.charge
        EventMailer.confirmed(invitee.user, event).deliver
      end
    end
  end

  def settle_without_payment
    invitees.each do |invitee|
      EventMailer.confirmed(invitee.user, event).deliver
    end
  end

  def closed?
    commit_date < Time.now
  end

  def self.open_events
    self.where('commit_date > ?', Time.now)
  end

  private

  def commit_date_is_in_the_future
    if commit_date && closed?
      errors.add(:commit_date, "must be in the future")
    end
  end

  def event_date_is_after_commit_date
    if start_time && start_time < commit_date
      errors.add(:start_time, "must be after commit date")
    end
  end

  def reject_empty_emails
    self.emails.reject!(&:blank?)
  end

  def contains_one_email
    if emails.first.blank?
     errors.add(:emails, "must include at least one invitee")
   end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event = Event.find_by_url(params[:id])
    @event.update_invitees_statuses(Group.new(@event.invitees).solve)
    session[:event_id] = @event.id
    @invitee = Invitee.find_by_user_id_and_event_id(current_user.id, @event.id)
    @all_comments = @event.comments

    if @event.emails.include?(current_user.email) || current_user.id == @event.creator_id
      @invitee = Invitee.find_or_create_by_user_id_and_event_id(current_user.id, @event.id)
    else
      flash[:error] = "You must be invited to the event to see this page"
      redirect_to :root
    end
  end

  def create
    emails = params[:event][:emails].values
    @event = Event.new(params[:event].merge(:emails => emails))

    if @event.save
      @event.emails.each {|email| UserMailer.event_invitee(email, current_user, @event).deliver }
      CreatorMailer.event_creation(current_user, @event).deliver
      flash[:success] = "Your new event was created successfully!"
      redirect_to event_path(@event.url)
    else
      flash[:error] = "An error occured while trying to make the event"
      redirect_to :back
    end
  end

  def update
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to event_path(@event) }
        format.json { respond_with_bip(@event) }
      else
        format.html { render :action => "edit" }
        format.json { respond_with_bip(@event) }
      end
    end
  end
end

app/views/events/_event_conditions.erb
<div class='conditional'>

  <h2> Will you attend? </h2>
  <div class="countdown">You have
  <span id="timeToCommit" data-commitDate="<%= @event.commit_date.to_i %>"></span>
  left to make up your mind.</div>
  <div class ='cond_buttons'>
    <% if @event.down_payment && @event.creator != current_user %>
      <button id="yes_with_payment" class="stripeButton", data-invitee_id=<%=invitee.id%>>yes</button>

      <%= form_tag charges_path, :class => "stripe_payment" do  %>
      <%= hidden_field_tag 'event_id', @event.id %>
      <%= hidden_field_tag 'status', 'Yes' %>
        <script>
        $('.stripeButton').click(function(){
          var token = function(res){
            var $input = $('<input type=hidden name=stripeToken />').val(res.id);
            $("form.stripe_payment").append($input).submit();
          };

          StripeCheckout.open({
            key:         "<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>",
            address:     false,
            amount:      "<%= event.down_payment %>",
            currency:    'usd',
            name:        'grouPACT',
            description: "<%= event.title %>",
            panelLabel:  'Commit to grouPACT',
            token:       token
          });

          return false;
        });
        </script>
      <% end %>


    <% else %>
      <button id='Yes', data-invitee_id=<%=invitee.id%>>yes</button>
    <% end %>
    <button id='yes_if' data-invitee_id=<%=invitee.id%>>yes, IF</button>
    <button id='No' data-invitee_id=<%=invitee.id%>>no</button>
  </div>
</div>

<div class="yes">
  <button id='close_window'> Close Window </button>
  <p>See you there!</p>
</div>

<div class='yes_if'>
  <p>What would it take to convince you to go?</p>
  <%= render :partial => "invitee_conditions", :locals => { :event => @event, :invitee => invitee } %>
</div>

<div class='thanks'>
  <button id='close_window'> Close Window </button>
  <p>We'll keep you posted!</p>
</div>

<div class ='no'>
  <button id='close_window'> Close Window </button>
  <p>Party Pooper.</p>
</div>

app/views/events/_event_display_comments.erb
<% all_comments.each do |comment| %>
  <% user = User.find(comment.user_id) %>
  <div class='full_comment'>
    <div class='comment_image'><%= image_tag user.profile_pic, {:size => '26x26'}%></div>
    <div class='comment_body'><%= comment.comment%></div>
    <div class='comment_posted_at'><%= link_to user.first_name, profile_path(user.url) %> - Posted <%= comment.time %> hours ago. </div>
  </div><br>
<% end %>

app/views/events/_event_info.erb
<% if event.closed? %>
  <div class="closed">
    <%= image_tag "events/expired.png", :height => "210" %>
  </div>
<% end %>
<%= image_tag @event.image, :class => "event_page_image", :size=>"440x210" %>
<% if event.down_payment %>
<span class="payment-required">
  The organizer of this event has required a payment of <%= number_to_currency(event.down_payment / 100.0) %> to RSVP.<br><br>
</span>
<% end %>
<h2>
  <%= best_in_place_if current_user.id == @event.creator_id, @event, :title, :type => :input %>
</h2>
<% if @event.start_time %>
<h5 id="start_time"><%= (@event.start_time - 5.hours).strftime("%A, %b %e at %l:%M %P CST") %></h5>
<% end %>
<h3 class='description'>
  <%=  best_in_place_if current_user.id == @event.creator_id, @event, :description, :type => :textarea, :nil => "click here to edit this field" %>
</h3>

app/views/events/_event_list.erb
<span class="condition-dropdown">
<%= link_to '< choose condition >', '#', :id=>'condition_link' %>
<ul id="condition_list">
  <li><%= link_to 'a certain person goes', '#', :id => 'certain_person_goes' %></li>
  <% if event.invitees.count > 1 %>
    <li><%= link_to 'a certain number go', '#', :id =>'number_of_people' %></li>
  <% else %>
    <li>a certain number go</li>
  <% end %>
</ul>
</span>

app/views/events/_event_new_comment.erb
<!-- why arent you using form_for? -->
 <%= form_tag({:controller => 'comments', :action=>'create'}, :method => 'post', :class=>'post_a_comment') do %>
  <%= text_field_tag "comment", nil, :placeholder=> "Leave a Comment"%>
  <!-- is this a security vulnerability? could a user set event id to something they shouldnt have access to? -->
  <%= hidden_field_tag 'event_id', event.id%>
  <%= button_tag("Comment", :id => "comment_button", :style => "display:none")%>
<% end %>

app/views/events/_event_sidebar.erb
<p>Event created by:</p>
<%= image_tag User.find(@event.creator_id).profile_pic.thumb, :class => "profile_pic", :size => "90x90" %>
<h2><%= link_to User.find(@event.creator_id).full_name, profile_path(User.find(@event.creator_id).url) %></h2>

<% unless @invitee.conditions.empty? && @invitee.status == "Pending" %>

<div id='condition-box'>
  <p >Your conditions </p>
  <ul id='your_conditions'>
    <% @invitee.conditions.each do |condition| %>
    <% if condition.method == 'specific_person' %>
    <li><%= User.find(condition.value).first_name %> needs to attend</li>
    <% elsif condition.method == 'required_count' %>
    <li><%= pluralize(condition.value, 'other person') %> must go</li>
    <% end %>
    <% end %>
  </ul>
  <span id='user_profile_pic'>
    <%= form_for @invitee, :url => reset_path(@invitee), :method => :post, :id=>"conditions_reset" do |f| %>
    <%= f.button "reset conditions", :id=>"reset_button" %>
    <% end %>
  </span>
</div>
<% end %>

<h3 class="bolder"><%= pluralize(event.emails.length + 1, "invitee") %></h3>

<% if event.going.count > 0 %>
<h3>Down to have fun:</h3>
<% event.going.each do |invitee| %>
<li class='invited'>
  <%= image_tag User.find(invitee.user_id).profile_pic.thumb, :size => '26x26' %>
  <%= link_to User.find(invitee.user_id).full_name, profile_path(User.find(invitee.user_id).url) %>
</li>
<% end %>
<% end %>

<% if event.waffling.count > 0 %>
<h3>Waffling:</h3>
<% event.waffling.each do |invitee| %>
<li class='invited'>
  <%= image_tag User.find(invitee.user_id).profile_pic.thumb, :size => '26x26' %>
  <%= link_to User.find(invitee.user_id).full_name, profile_path(User.find(invitee.user_id).url) %>
</li>
<% end %>
<% end %>

<% if event.not_going.count > 0 %>
<h3>Missing out:</h3>
<% event.not_going.each do |invitee| %>
<li class='invited'>
  <%= image_tag User.find(invitee.user_id).profile_pic.thumb, :size => '26x26' %>
  <%= link_to User.find(invitee.user_id).full_name, profile_path(User.find(invitee.user_id).url) %>
</li>
<% end %>
<% end %>

app/views/events/_invitee_conditions.html.erb
<div class="condition-builder">
  <%= form_tag({:controller => 'conditions', :action=>'create'}, :method => 'post', :class => "stripeYesIF") do %>
  <div id="sentence">I will attend this event <span class='bolder'>IF</span> <%=render :partial => "event_list", :locals => { :event => event }%></div><br>
  <%= hidden_field_tag 'invitee_id', invitee.id%>
  <%= hidden_field_tag 'event_id', event.id %>
  <% if event.down_payment && event.creator != current_user %>
      <button id="condition_button" class="stripeButton", data-invitee_id=<%=invitee.id%>>Commit</button>

      <%= form_tag charges_path, :class => "stripe_payment" do  %>
      <%= hidden_field_tag 'event_id', event.id %>
      <%= hidden_field_tag 'status', 'Pending' %>
        <script>
        $('.stripeButton').click(function(){
          var token = function(res){
            var $input = $('<input type=hidden name=stripeToken />').val(res.id);
            $("form.stripe_payment").append($input).submit();
          };

          StripeCheckout.open({
            key:         "<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>",
            address:     false,
            amount:      "<%= event.down_payment %>",
            currency:    'usd',
            name:        'grouPACT',
            description: "<%= event.title %>",
            panelLabel:  'Commit to grouPACT',
            token:       token
          });

          return false;
        });
        </script>
      <% end %>
    <% else %>
      <%= button_tag("Commit", :id => "condition_button")%><br>
    <% end %>
  <% end %>
</div>

<div class="hide">
  <span id="minNumSelection">
    at least <%= select(:event, :invitees, (2..event.emails.length + 1)) %> people go
  </span>

  <span id="personSelection">
    <%= collection_select(:event, :users, event.users.where("status != 'No'"), :id, :full_name, {}, {:id => "event", :name => "event[users][]"}) %> goes
  </span>
</div>

app/views/events/show.html.erb
<% if !@event.creator_api && @event.creator == current_user && @event.down_payment %>
  <div id="stripe_link">
    <p>To collect payments from attendees, please...</p>
    <%= link_to image_tag('/assets/stripe_light.png'), "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=#{ENV['STRIPE_CLIENT_ID']}&scope=read_write" %>
    <p class="stripe-msg">Don't be intimidated by Stripe's form. Feel free to use your grou<span class="bolder">pact</span> <%= link_to 'personal profile URL', profile_path(current_user.url), :target => '_blank' %> as your 'Product Website.' No tax information needs to be entered, and you can use your full name in place of 'Business Name.' That's it, soon you'll be able collect downpayments for your event.</p>
  </div>
<% end %>

<div class="wrapper" id="<%= @event.url %>">

  <div class="event_info"> <!-- Main Column -->

    <% unless @invitee.responded || @event.closed? %>
      <%= render :partial => "event_conditions", :locals => { :event => @event, :invitee => @invitee } %>
    <% end %>
    <%= render :partial => "event_info", :locals => { :event => @event } %>

    <div id="comment_area">
      <% if @all_comments %>
        <%= render :partial => "event_display_comments", :locals => { :all_comments => @all_comments } %>
      <% end %>
      <%= render :partial => "event_new_comment", :locals => { :event => @event } %>
    </div>

  </div>

  <div class ='vertical'> <!-- Left Column -->
    <%= render :partial => "event_sidebar", :locals => { :event => @event, :invitee => @invitee } %>
  </div>

  <div class="clear"></div>

</div>