config/routes.rb
Planning::Application.routes.draw do

  resources :sessions, :only => [:create, :new]
  resources :events
  resources :users
  resources :conditions
  resources :comments
  resources :charges

  root :to => 'home#index'

  get  '/logout/'                 => 'sessions#logout', :as => 'logout'
  post '/invitees/:id'            => 'invitees#update', :as => 'update'
  get  '/users/:slug/admin'       => 'users#admin',     :as => 'admin'
  get  '/users/:slug/profile'     => 'users#profile',   :as => 'profile'
  post '/invitees/:id/conditions' => 'invitees#reset',  :as => 'reset'
  get  '/about'                   => 'home#about'
  get  '/stripe'                  => 'users#stripe'
  post '/validate/email'          => 'users#validate_email'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/views/layouts/_alerts.erb
<% if flash %>
  <% flash.each do |k, v| %>
    <div class="<%= flash_class(k) %>"><%= v %></div>
  <% end %>
<% end %>

app/views/layouts/_footer.erb
<% if current_user %>
  <footer>
    you are logged in as <%= link_to current_user.full_name, profile_path(current_user.url) %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to "your portal", admin_path(current_user.url) %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to "about", about_path %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;
    <%= link_to "sign out", logout_path %>
  </footer>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>grouPACT</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "https://checkout.stripe.com/v2/checkout.js", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<a id="top"></a> <!-- For Scrolling JQuery -->

<h1><%= link_to "home", root_path %></h1>

<%= render :partial => "layouts/alerts" %>

<%= yield %>

<%= render :partial => "layouts/footer" %>


</body>
</html>